/* 
.......... DIBAKAR SUTRA DHAR ...........
....... iamdibakardipu@gmail.com ........
.............. dibakar.me ...............
.........................................
............... CS50x ...................
............. HELLO WORLD ...............
*/


#include <stdio.h>

int main(void) {
	printf("Hello, world!\n");
}